[build.environment]
  NPM_FLAGS = "--version"
  NODE_VERSION = "22"

[build]
  publish = "doc_build"
  command = "npx pnpm run docs:build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
